# Generated by Django 4.1.5 on 2023-01-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_delete_snippetserializer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
